-- CREATE TABLE für `lebtab`
-- Quelle: c_LTAB3_082026_V1_Strukturänderung.xlsx (Sheet "data")
-- Alle Spalten mit lebtab_ Präfix zur Unterscheidung von anderen Tabellen (analog LEBTAB_Tabelle, anreich_tabelle).
-- `lebtab_lmc` ist eindeutig (20.315 Werte, 0 Duplikate, 0 leer) und dient als PRIMARY KEY,
-- über den `c_zutab` später per FOREIGN KEY verknüpft werden kann. Engine InnoDB +
-- CHAR(6)/utf8mb4_unicode_ci, damit die künftige FK aus c_zutab typ- und collationgleich ist.

CREATE TABLE IF NOT EXISTS `lebtab` (
  `lebtab_lmc`  CHAR(6)  NOT NULL,
  `lebtab_Bezeich`  VARCHAR(255)  NOT NULL,
  `lebtab_Marke`  VARCHAR(191)  NULL,
  `lebtab_Version`  INT  NULL,
  `lebtab_Itemart`  VARCHAR(5)  NOT NULL,
  `lebtab_Datum`  DATE  NOT NULL,
  `lebtab_aktuell`  INT  NOT NULL,

  `lebtab_E_CAL`  DOUBLE  NULL,
  `lebtab_E_JOULE`  DOUBLE  NULL,
  `lebtab_EW`  DOUBLE  NULL,
  `lebtab_t_ew`  DOUBLE  NULL,
  `lebtab_FETT`  DOUBLE  NULL,
  `lebtab_KH`  DOUBLE  NULL,
  `lebtab_ALKO`  DOUBLE  NULL,
  `lebtab_H2O`  DOUBLE  NULL,
  `lebtab_FiB`  DOUBLE  NULL,
  `lebtab_L_FIB`  DOUBLE  NULL,
  `lebtab_U_FIB`  DOUBLE  NULL,
  `lebtab_Gluc`  DOUBLE  NULL,
  `lebtab_Fruc`  DOUBLE  NULL,
  `lebtab_Galac`  DOUBLE  NULL,
  `lebtab_MSacch`  DOUBLE  NULL,
  `lebtab_Sacch`  DOUBLE  NULL,
  `lebtab_MALT`  DOUBLE  NULL,
  `lebtab_LACT`  DOUBLE  NULL,
  `lebtab_DISACCH`  DOUBLE  NULL,
  `lebtab_ZUCK`  DOUBLE  NULL,
  `lebtab_STAERKE`  DOUBLE  NULL,
  `lebtab_GI`  DOUBLE  NULL,
  `lebtab_zuzu`  DOUBLE  NULL,
  `lebtab_frzu`  DOUBLE  NULL,
  `lebtab_CHOL`  DOUBLE  NULL,
  `lebtab_S_FS`  DOUBLE  NULL,
  `lebtab_M_FS`  DOUBLE  NULL,
  `lebtab_P_FS`  DOUBLE  NULL,
  `lebtab_F180`  DOUBLE  NULL,
  `lebtab_F181`  DOUBLE  NULL,
  `lebtab_F182`  DOUBLE  NULL,
  `lebtab_F183`  DOUBLE  NULL,
  `lebtab_F204`  DOUBLE  NULL,
  `lebtab_F205`  DOUBLE  NULL,
  `lebtab_F226`  DOUBLE  NULL,
  `lebtab_v_A`  DOUBLE  NULL,
  `lebtab_CAROT`  DOUBLE  NULL,
  `lebtab_V_D`  DOUBLE  NULL,
  `lebtab_v_e`  DOUBLE  NULL,
  `lebtab_V_K`  DOUBLE  NULL,
  `lebtab_V_B1`  DOUBLE  NULL,
  `lebtab_V_B2`  DOUBLE  NULL,
  `lebtab_NIACI`  DOUBLE  NULL,
  `lebtab_PANTO`  DOUBLE  NULL,
  `lebtab_V_B6`  DOUBLE  NULL,
  `lebtab_BIOTI`  DOUBLE  NULL,
  `lebtab_FOL_EQ`  DOUBLE  NULL,
  `lebtab_V_B12`  DOUBLE  NULL,
  `lebtab_V_C`  DOUBLE  NULL,
  `lebtab_NATR`  DOUBLE  NULL,
  `lebtab_KALI`  DOUBLE  NULL,
  `lebtab_CALC`  DOUBLE  NULL,
  `lebtab_MAGN`  DOUBLE  NULL,
  `lebtab_PHOS`  DOUBLE  NULL,
  `lebtab_EISE`  DOUBLE  NULL,
  `lebtab_ZINK`  DOUBLE  NULL,
  `lebtab_KUPF`  DOUBLE  NULL,
  `lebtab_MANG`  DOUBLE  NULL,
  `lebtab_JOD`  DOUBLE  NULL,
  `lebtab_ISO`  DOUBLE  NULL,
  `lebtab_LEU`  DOUBLE  NULL,
  `lebtab_LYS`  DOUBLE  NULL,
  `lebtab_MET`  DOUBLE  NULL,
  `lebtab_CYS`  DOUBLE  NULL,
  `lebtab_PHE`  DOUBLE  NULL,
  `lebtab_TYR`  DOUBLE  NULL,
  `lebtab_THR`  DOUBLE  NULL,
  `lebtab_TRY`  DOUBLE  NULL,
  `lebtab_VAL`  DOUBLE  NULL,
  `lebtab_ARG`  DOUBLE  NULL,
  `lebtab_HIS`  DOUBLE  NULL,
  `lebtab_ESSAS`  DOUBLE  NULL,
  `lebtab_ALA`  DOUBLE  NULL,
  `lebtab_ASP`  DOUBLE  NULL,
  `lebtab_GLU`  DOUBLE  NULL,
  `lebtab_GLY`  DOUBLE  NULL,
  `lebtab_PRO`  DOUBLE  NULL,
  `lebtab_SER`  DOUBLE  NULL,

  `lebtab_NESSAS`  DOUBLE  NULL,
  `lebtab_lmgruppe`  INT  NULL,
  `lebtab_name_lmgruppe`  VARCHAR(100)  NULL,
  `lebtab_source`  VARCHAR(45)  NULL,
  `lebtab_source_code`  VARCHAR(45)  NULL,
  `lebtab_source_detail`  VARCHAR(100)  NULL,
  `lebtab_probiotisch`  INT  NULL,

  PRIMARY KEY (`lebtab_lmc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
